# Generated by Django 3.2.12 on 2023-11-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mobile'),
        ('users', '0002_user_mobile_user_otp'),
    ]

    operations = [
    ]
